### ISSUE TITLE
MicroPython support?

### ISSUE THREAD

**Issue by andypiper** [ElectronicCats/BomberCat#1]
The store page mentions that the board will support MicroPython, do you have a firmware and examples for this already that we could look at?

**Comment by jazhe** [comment]
Hello @andypiper 

Currently, we are working on adding more examples!
Keep up with our updates here, we will publish them later on. 😊

Hope you have a nice day!
Electronic Cats Support Team

**Comment by andypiper** [comment]
Great, I may order one if there is a MicroPython board definition and source available.
